url: http://www1.macys.com
url3: http://www.google.com
url5: http://www.qacreative1macys.fds.com
url_pp_chk1: http://www1.preprod5macys.fds.com/  
navigation:
  forthehome: home
  bed&bath: bath
  women: women
  men: men
  juniors: juniors
  kids: kids
  beauty&fragrance: beauty
  shoes: shoes
  handbags&accessories: handbags
  jewelry&watches: jewelry
  sale: sale