url: http://www1.mcomtest030.fds.com
url1: http://www.preprod8bloomingdales.fds.com
navigation:
  forthehome: home
  bed&bath: bath
  women: women
  men: men
  juniors: juniors
  kids: kids
  beauty&fragrance: beauty
  shoes: shoes
  handbags&accessories: handbags
  jewelry&watches: jewelry
  sale: sale
